CREATE TABLE school_master (
	schoolId bigint NOT NULL,
	stateId smallint NOT NULL,
	districtId int NOT NULL,
	blockId int NOT NULL,
	clusterId bigint NOT NULL,
	villageId int NOT NULL,
	schoolName varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	schoolCategoryId int NOT NULL,
	schoolManagementId int NOT NULL,
    isVisible BIT NULL,
    isPrintVovcherAllowed BIT NULL,
    schemeName VARCHAR(10),
	isPrePrimary bit DEFAULT 0 NOT NULL,
	isBalvatika bit DEFAULT 0 NOT NULL,
	lowerClass smallint NOT NULL,
	upperClass smallint NOT NULL,
	principalName varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	principalMobile varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	principalEmail varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	isMerged bit DEFAULT 0 NULL,
	mergedYear smallint NULL,
	mergedSchoolId bigint NULL,
	isClosed bit DEFAULT 0 NULL,
	closedYear smallint NULL,
	isActive bit DEFAULT 1 NOT NULL,
	inactiveReason int NULL,
	isNICApproved bit NULL,
	isCWSNSchool bit NULL,
	zoneId smallint NULL,
	schoolLocality smallint NULL,
	mediums varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	academicYear varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	studentsEnrolledInCurrentYear smallint DEFAULT 0 NULL,
	schoolTypeBundleId int NULL,
	schoolBoardID varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	schoolType smallint NULL,
	isMultipleMediums bit NULL,
	isSchoolVocational bit NULL,
	schoolStream varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	createdBy bigint NULL,
	updatedBy bigint NULL,
	createdAt datetime DEFAULT sysdatetime() NOT NULL,
	updatedAt datetime DEFAULT sysdatetime() NOT NULL,
	ipAddress varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK_school_master PRIMARY KEY (schoolId),
	);
