CREATE TABLE student_reset_logs
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    childUID BIGINT,
	userId INT,
    resetType VARCHAR(30),   -- REGISTRATION_FORM_RESET / APPROVER_RESET / CHOICE_FILLING_RESET
    resetReason NVARCHAR(500),
    createdAt DATETIME2 DEFAULT SYSDATETIME(),
    ipAddress VARCHAR(25)
);
