CREATE TABLE student_data_reset_log
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    childUID BIGINT NOT NULL,
    schoolId BIGINT,
    studentName NVARCHAR(100) NULL,
    fatherName NVARCHAR(100) NULL,
    surname NVARCHAR(100) NULL,
    genderId INT NULL,
    birthDate DATE NULL,
    birthCertificateDocument NVARCHAR(255) NULL,
    categoryId INT NULL,
    castCertificateDocument NVARCHAR(255) NULL,
    subCategoryId INT,
    subCategoryDocument NVARCHAR(255) NULL,
    psId INT NULL,
    psDocument NVARCHAR(255) NULL,
    isLandDonor BIT NULL,
    landDonorDocument NVARCHAR(255) NULL,
    isDisabilityMoreThen40 BIT NULL,
    disabilityPercentage INT NULL,
    disabilityType INT NULL,
    disabilityCertificateDocument NVARCHAR(255) NULL,
    isStd1To5GovtGrantCompleted BIT NULL,
    addressDistrictId INT NULL,
    addressBlockId INT NULL,
    addressVillageId INT NULL,
    domicileCertificate NVARCHAR(255) NULL,
    parentMo VARCHAR(10) NULL,
    isRegistered BIT NULL,
    isApproved BIT NULL,
    createdAt DATETIME2(3) DEFAULT SYSDATETIME(),
    ipAddress VARCHAR(25) NULL
);
